# -*- coding: utf-8 -*-
"""Task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e3Mci_iHEbxre3nuIWMRc_JFcGler2zw

##Program for Convert from Celsius to Fahrenheit
"""

cel= float(input('Enter the temperature in Celsius  "C" : ' ))
feh = cel*(9/5)+32
print(f"The temperature in Fahrenheit = {chr(176)}{feh}")