# -*- coding: utf-8 -*-
"""Task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e3Mci_iHEbxre3nuIWMRc_JFcGler2zw

##Program for Convert from Celsius to Fahrenheit
"""

cel= float(input('Enter the temperature in Celsius  "C" : ' ))
feh = cel*(9/5)+32
print(f"The temperature in Fahrenheit = {chr(176)}{feh}")

"""###Enhancement for the program"""

chose = input("Enter the temperature you wnat to convert 'C' for Celsius  and 'F'Fahrenheit : ")
temper= float(input("Enter the temperature : "))
flag= False
calctemp= 0
while flag == False:

  if chose.upper()=="C":
    calctemp= temper*(9/5)+32
    print(f"The convert form Celsius to Fahrenheit is {chr(176)}{calctemp}")
    flag == True
    break
  elif chose.upper()=="F":
    calctemp= (temper -32)*(5/9)
    print(f"The convert form Fahrenheit to Celsius is {chr(176)}{calctemp}")
    flag == True
    break
  else:
    print("Error")
    chose = input("Enter the temperature you wnat to convert 'C' for Celsius  and 'F'Fahrenheit : ")